dist: bionic
install:
  #- sudo dpkg --purge packages-microsoft-prod && sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.2
script:
  - dotnet test